@baseUrl = http://localhost:3001

###
# -------------------------
# @name QueryHealth
GET {{baseUrl}}/health
Authorization: Bearer {{accessToken}}

###
# -------------------------
# @name CmdTemp
POST {{baseUrl}}/temp

# ==================================

###
# -------------------------
# @name CmdSignUp
POST {{baseUrl}}/auth/sign-up

{
  "email": "user51@gmail.com",
  "password": "pass",
  "fullName": "Halo"
}

###
# -------------------------
# @name CmdVerify
POST {{baseUrl}}/auth/verify

{
  "userId": "67da8598625c22786e43c0a1",
  "token": "cb0db12622c4092dce9fa157b4fb6aab"
}

###
# -------------------------
# @name CmdLogin
POST {{baseUrl}}/auth/login

{
  "email": "user51@gmail.com",
  "password": "pass2"
}

###
# -------------------------
# @name CmdForgetInit
POST {{baseUrl}}/auth/forget-password/init

{
  "email": "user51@gmail.com"
}

###
# -------------------------
# @name CmdForgetSet
POST {{baseUrl}}/auth/forget-password/set

{
  "userId": "67da8598625c22786e43c0a1",
  "token": "7c5b2330b627ca0aac56e19ca827fc76",
  "newPassword": "pass2"
}


###
@accessToken = {{CmdLogin.response.body.$.accessToken}}


