@baseUrl = http://localhost:3001

###
# -------------------------
# @name QueryHealth
GET {{baseUrl}}/health
Authorization: Bearer {{accessToken}}

###
# -------------------------
# @name CmdTemp
POST {{baseUrl}}/temp

# ==================================

###
# -------------------------
# @name CmdSignUp
POST {{baseUrl}}/auth/sign-up

{
  "email": "user50@gmail.com",
  "password": "pass",
  "fullName": "User 4"
}

###
# -------------------------
# @name CmdVerify
POST {{baseUrl}}/auth/verify

{
  "userId": "67da7b1466769157950b8673",
  "token": "2ce28f7ad3706219f2ad39b5addf96ba"
}

###
# -------------------------
# @name CmdLogin
POST {{baseUrl}}/auth/login

{
  "email": "user1@gmail.com",
  "password": "pass"
}

###
# -------------------------
# @name CmdForgetInit
POST {{baseUrl}}/auth/forget-password/init

{
  "email": "user2@gmail.com"
}

###
# -------------------------
# @name CmdForgetSet
POST {{baseUrl}}/auth/forget-password/set

{
  "userId": "67d9cb4047e29e1523ca4f24",
  "token": "adcb66df8df34a410f547420c3580f50",
  "newPassword": "pass2"
}


###
@accessToken = {{CmdLogin.response.body.$.accessToken}}


