name: Build & Test FrameCraft API

on:
  pull_request:
    branches: [main, develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js & pnpm
        uses: actions/setup-node@v3
        with:
          node-version: '23.9.0'
          cache: 'pnpm'

      - name: Install pnpm
        run: npm install -g pnpm@10.7.0

      - name: Install dependencies and build
        run: |
          pnpm install
          pnpm build
