name: Build and Deploy FrameCraft API

on:
  push:
    branches: [main]

env:
  ACR_NAME: framecraftregistry.azurecr.io
  IMAGE_NAME: framecraft-api
  RESOURCE_GROUP: FrameCraftResourceGroup
  WEBAPP_NAME: FrameCraftApi2

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js & pnpm
        uses: actions/setup-node@v3
        with:
          node-version: '23.9.0'
          cache: 'pnpm'

      - name: Install pnpm
        run: npm install -g pnpm@10.7.0

      - name: Install dependencies and build
        run: |
          pnpm install
          pnpm build

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Log in to ACR
        run: |
          echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login $ACR_NAME -u ${{ secrets.REGISTRY_USERNAME }} --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t $IMAGE_NAME .
          docker tag $IMAGE_NAME $ACR_NAME/$IMAGE_NAME:latest
          docker push $ACR_NAME/$IMAGE_NAME:latest

      - name: Restart Azure Web App
        run: |
          az webapp restart \
            --name $WEBAPP_NAME \
            --resource-group $RESOURCE_GROUP
